services:
  evalia-frontend:
    container_name: frontend-evalia
    hostname: frontend-evalia
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3001:5173"
    command: sh -c "npm install && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://backend-evalia:8000
    restart: always
    networks:
      - evalia-net

volumes:
  cache:
    driver: local  
  data:
    driver: local

networks:
  evalia-net:
    name: evalia-net
    external: true